<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>d65cd9c6-9df3-464e-a023-07030932486b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Python" />
    <PackageReference Include="Aspire.Hosting.Azure.ApplicationInsights" />
    <PackageReference Include="Aspire.Hosting.Azure.AppContainers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspirePy.Web\AspirePy.Web.csproj" />
  </ItemGroup>

</Project>
